<a href="https://colab.research.google.com/github/ed-roberts-github/Previous-work/blob/main/Artificial_Neural_Network(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
tf.__version__ #print version of tf using (as already installed in google colab)

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #missing out first 3 cols (and last) (Neural network should figure this out but eases laerning process)
y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
#remember no need for one hot encoding as only 2 options
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])] , remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X) #remember dummy (encoded) variables moved to front

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
#creating variable that will be the ANN (as a sequence of layers)
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

No rule of thumb to choose the number of neurons, just have to play around

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) 
#units is the number of neurons in the first hidden layer
#actiavtion = 'relu' sets the activation functions to the rectifier function

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  
#exact same as above, .add can be used to add layer at any lvl

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) 
#1 output as 1 binary dependant variable
#need sigmoid function for last layer as well as it will give probabilty of customer leaving the bank

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])  
#using stochastic grad descent (adam)
#binary classification (for non-bin classification 'crossentropy' and activation should be softmax)

### Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) 
#batch size of 32 is the standard choice  
#epochs is the number of passes of the entire training dataset by the learning algorithm

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5514 - accuracy: 0.7445
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4762 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4530 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4360 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4248 - accuracy: 0.8191
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4177 - accuracy: 0.8216
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4122 - accuracy: 0.8261
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4074 - accuracy: 0.8288
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4040 - accuracy: 0.8295
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4007 - accura

Note it converged to 0.86 before the end of the 100 epochs

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [24]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 5000]])))
#same as in earlier parts of the course :) 
#remember the double pair [[]] and to scale correctly

[[0.04079849]]


Remember used the sigmoid function so are getting the probabity that the customer will leave the bank

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #converting probabilties into binary answer
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1509   86]
 [ 197  208]]


0.8585