CNN 0-9 classifier using the MNIST data set

In [20]:
import tensorflow as tf
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
tf.__version__

'2.6.0'

In [21]:
#luckily mnist is included in the keras libary!!
#I found this code of how to import the data online
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#I used this to understand format of arrays
print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", y_test.shape)
print(y_train)
print(y_test)

X_train shape (60000, 28, 28, 1)
y_train shape (60000,)
X_test shape (10000, 28, 28, 1)
y_test shape (10000,)
[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [22]:
#future scaling
X_train = X_train /255
X_test = X_test / 255

In [23]:
#one hot encoding the y data classification(0-9)
#Note this si a quicker way than i learnt on the course, as it turns out theres a class in keras that can do it directly
from keras.utils import np_utils as npu
y_train = npu.to_categorical(y_train)
y_test = npu.to_categorical(y_test)
print(y_train)
print(y_test)
print(np.argmax(y_train[0]))
print(np.argmax(y_test[0]))
#np.argmax can be used to undo one hot encoding

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
5
7


In [24]:
#Building CNN

cnn = tf.keras.models.Sequential() 

#convolution
cnn.add(tf.keras.layers.Conv2D(filters = 25, kernel_size = 3, activation = 'relu', input_shape = [28,28,1]))
#pooling
cnn.add(tf.keras.layers.MaxPool2D(pool_size = 2, strides = 2))

#second convolution and pooling
cnn.add(tf.keras.layers.Conv2D(filters = 25, kernel_size = 3, activation = 'relu', input_shape = [28,28,1]))
cnn.add(tf.keras.layers.MaxPool2D(pool_size = 2, strides = 2))

#flattening
cnn.add(tf.keras.layers.Flatten())

#adding ANN layers
cnn.add(tf.keras.layers.Dense(units = 120, activation = 'relu'))
cnn.add(tf.keras.layers.Dense(units = 10, activation = 'softmax')) 

In [25]:
#training

cnn.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

cnn.fit(x = X_train,y = y_train, validation_data = (X_test,y_test), epochs = 5, batch_size = 128)

Epoch 1/5
469/469 [==============================] - 24s 51ms/step - loss: 0.2667 - accuracy: 0.9230 - val_loss: 0.0744 - val_accuracy: 0.9779
Epoch 2/5
469/469 [==============================] - 24s 50ms/step - loss: 0.0703 - accuracy: 0.9783 - val_loss: 0.0522 - val_accuracy: 0.9835
Epoch 3/5
469/469 [==============================] - 27s 58ms/step - loss: 0.0489 - accuracy: 0.9847 - val_loss: 0.0440 - val_accuracy: 0.9870
Epoch 4/5
469/469 [==============================] - 25s 53ms/step - loss: 0.0387 - accuracy: 0.9879 - val_loss: 0.0340 - val_accuracy: 0.9886
Epoch 5/5
469/469 [==============================] - 25s 54ms/step - loss: 0.0304 - accuracy: 0.9905 - val_loss: 0.0365 - val_accuracy: 0.9886


99% accuracy seems good too good to be true?!?!